### ISSUE TITLE
Upload this project to central?

### ISSUE THREAD

**Issue by Leguan16** [Ratsiiel/region-library#1]
Hey! 

I am recently looking for a way to read region files and I think this could be a good lib. 

Unfortunately I dont see any sign that you uploaded it to central. 
Would you consider doing it or can you give me permissions so that I can upload it (if you dont want to waste your time with it)? 
It would make the implementation much easier since you just add the dependency to your build.gradle/pom file.

**Comment by Ratsiiel** [comment]
Hey.

I will soon upload the library to maven-central as you wished.

**Comment by Leguan16** [comment]
Thank you for the quick reply.

I hope I dont bother you with it.

**Comment by Ratsiiel** [comment]
You do not bother me.
If you want to use the library now, it is also possible to use it from here.

repositories {
    maven {
        url "http://repo.ratsiel.me"
    }
}

**Comment by Leguan16** [comment]
I see.

I have another question:

Are you planning on adding a feature to write on the region files. If not I would consider updating the library if you are interested.

**Comment by Ratsiiel** [comment]
I wanted to make it possible to write region files in the near future. 
But if you feel like completing this, you are welcome to do so.

**Comment by Leguan16** [comment]
Great. 
Have a nice day and merry christmas
